name: Refresh ICS file

on:
  # schedule:
  #   - cron: '25 12 * * *'
  workflow_dispatch:

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          sudo apt-get install python3-lxml
          # Not using '-r requirements.txt' here because 'python3-lxml' installed above
          python -m pip install icalendar requests
      - name: Fetch data and produce prodcal.ics
        run: python prodcal_ics.py --start-year=2018 -o /tmp/prodcal.ics
      - uses: actions/upload-artifact@v2
        with:
          name: prodcal.ics
          path: /tmp/prodcal.ics

  upload:
    runs-on: ubuntu-latest
    needs: fetch
    steps:
      - uses: actions/checkout@v2
        with:
          ref: gh-pages

      - uses: actions/download-artifact@v2
        with:
          name: prodcal.ics

      - name: Push changes if any
        run: |
          if [[ $(git status -s prodcal.ics) ]]; then
            git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git config --local user.name "github-actions[bot]"

            git add prodcal.ics && \
            git commit -m "Update prodcal.ics" && \
            git push
          fi
