name: Refresh ICS file

on:
  schedule:
     - cron: '0 0 * * 1'
  workflow_dispatch:

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: sudo apt-get install libxml2-dev libxslt-dev
      - uses: actions/setup-python@v5
        with:
          python-version: 3.8
          cache: 'pip'
      - run: pip install -r requirements.txt
      - name: Fetch data and produce krasnodar_stadium.ics
        run: python krasnodar_stadium_ics.py -o /tmp/krasnodar_stadium.ics
      - uses: actions/upload-artifact@v4
        with:
          name: krasnodar_stadium.ics
          path: /tmp/krasnodar_stadium.ics

  upload:
    runs-on: ubuntu-latest
    needs: fetch
    steps:
      - uses: actions/checkout@v4
        with:
          ref: gh-pages

      - uses: actions/download-artifact@v4
        with:
          name: krasnodar_stadium.ics

      - name: Push changes if any
        run: |
          if [[ $(git status -s krasnodar_stadium.ics) ]]; then
            git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git config --local user.name "github-actions[bot]"

            git add krasnodar_stadium.ics && \
            git commit -m "Update krasnodar_stadium.ics" && \
            git push
          fi
